### PR TITLE
docs: move to VuePress

### PR DESCRIPTION
**Pull request by eddyerburgh**
[ ] Add config docs
[ ] Add Japanese translations to config.js
[ ] Link Chinese translations correctly
[ ] Link Japanese translations correctly
[ ] Add redirects

### CODE REVIEW

**Comment by Jinjiang** [comment]
Any help needed for Chinese translation please let me know.

**Comment by eddyerburgh** [comment]
Thanks @Jinjiang 😄 

I need Chinese translations for:
`Utilities for testing Vue components`

And @38elements I need Japanese translations for:
`Utilities for testing Vue components`
`Japanese`
`Languages`
`Edit this page on GitHub`

Thank you 🙏

**Comment by 38elements** [comment]
Utilities for testing Vue components  -> Vue コンポーネントをテストするためのユーティリティ
Japanese -> 日本語
Languages -> 言語
Edit this page on GitHub -> GitHub 上でこのページを編集する

**Comment by Jinjiang** [comment]
`Utilities for testing Vue components` -> `测试 Vue 组件的实用工具`

**Comment by kazupon** [comment]
🎉

**Comment by ulivz** [comment]
🎉

**Comment by lex111** [comment]
Hey!

Why were other translations removed? How can I restore Russian translation?

**Comment by eddyerburgh** [comment]
@lex111 unfortunately we can only support languages that receive regular updates. If the translations are not updated regularly, they become out of sync with the real documentation.

I'm grateful for the work translating the docs to different languages, but it's difficult for us to keep these translations up-to-date, especially if no core team members speak the language. Some of the translations we had were very out of date. 

The plan was to remove all translations except Chinese, but the Japanese translations also receive very regular (several times a week) updates, so we know they will be kept up to date.

You are welcome to fork and host the translation on their own, but we no longer have the bandwidth to include them in official repos

**Comment by lex111** [comment]
@eddyerburgh I understand you, but we actively support translations, you probably know that about our community (https://github.com/translation-gang/), which also maintains an up-to-date official website with Vue documentation in Russian.

As for the documentation for this tool, it was not very old, we are not comfortable with tracking changes (maybe we do not know how to do it right or better, it's possible to track updates in automatic or semi-automatic mode? Please share with us the best practices about translation actualization), and then we are used to having your own repository for translation when is possible, because it's more convenient to us to do translation updates.

But give us you another chance, updates for Russian documentation are not very big, we feel sorry if our work is lost, because fewer people will know about the existence of the translation :cry: 

We are a community of translators, we are not so many, but we want and try to keep the documents up-to-date, we are interested in it!

**Comment by lex111** [comment]
@eddyerburgh 

Since now you generate documentation using your own tool, I suggest that you consider the next possibility associated with translations.

What if we do not delete _all the translations_, even if they have not been updated for a long time, but to _mark_ them, that they are obsolete? It's easier to show by example, see how it's done at https://elixirschool.com
I will specify better, I mean something like an indicator of the relevance of the translation, and now I'll show you how it looks.

When the translation is relevant (no needs updates, it's synchronized), the "green circle" will be displayed
Page - https://elixirschool.com/en/lessons/basics/basics/
image

But, for example, on [this](https://elixirschool.com/ru/lessons/basics/pattern-matching/) page the translation _needs to be updated_ (it's not synchronized), and now you can see the "orange circle", which means that the content on this page (translation) is out of date (_needs to be updated_), because the original doc was slightly updated.

image

And there is also a "red circle", which indicates that the translation is _very outdated_. For example, this is now on [this](https://elixirschool.com/ru/lessons/libraries/poolboy/) page.

image

How do you like this idea? It would be cool to implement this, what are the advantages?
- (_most importantly_) Remain all translations (this is the work of people, someone, even the old version, will benefit, plus it will motivate other people to update the translation in accordance with the original, I want to believe it! :smiley: )
- You can visually find out that the translation is up-to-date or not, it is useful, both for translators, for and for readers of translation.
- Just as a suggestion, leave everything as is :)

Thus, you discharge your responsibility by making an explanatory message (for example, that the translation is out of date, refer to the original), if the translation is out of date, and other people, for example, can update it. Think about it, it's a good idea, in my opinion!

**Comment by eddyerburgh** [comment]
@lex111 Sorry for the delayed response.

If you guys can keep the translations in sync then we can host them again. 

Next time, if they are out of sync I will remove them temporarily until they are updated. I won't remove them from the repo completely without first speaking with you.

**Comment by lex111** [comment]
@eddyerburgh 

And what about the indication of the translation described in [the comment](https://github.com/vuejs/vue-test-utils/pull/627#issuecomment-391475550)?

Can there be any recommendations to keep the documentation up to date?

Now we need PR with an actual Russian translation?

**Comment by eddyerburgh** [comment]
At the moment, the plan is to remove them temporarily if they become out of date.

I don't have recommendations for keeping translations up to date. @38elements do you have suggestions for keeping translations up to date?

Yes, we'll accept a PR with translations.

**Comment by 38elements** [comment]
You can check the change history at below page.
It is better to check the page and translate the changes at once a week.

English document of API
https://github.com/vuejs/vue-test-utils/commits/dev/docs/api

English document of guides
https://github.com/vuejs/vue-test-utils/commits/dev/docs/guides

All document
https://github.com/vuejs/vue-test-utils/commits/dev/docs

**Pull request merged**
