### PR TITLE
docs: fix prettier errors in zh docs

### PR DESCRIPTION
**Pull request by alexmiddeleer**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ X ] Other, please describe:
Fix lint in docs

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [ X] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ X] It's submitted to the `dev` branch.
- [ X] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ X] All tests are passing: https://github.com/vuejs/vue-test-utils/blob/dev/.github/CONTRIBUTING.md#development-setup
- [ X] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

This is how the changed bit of documentation looks now. I do not read Chinese so I cannot verify for certain that it is correct: 

image

### CODE REVIEW

**Review by afontcu — APPROVED** [review]

**Comment by Justineo** [comment]
Hi, thanks for the contribution! But we are now intentionally using `*` instead of `_` in the Chinese version because they are not equivalent in GFM and `_` would lead to some bad cases for the Chinese version.

**Comment by alexmiddeleer** [comment]
I was worried about that. Let me know if I can help with anything such as
tweaking the prettier config to make the tests pass again.

**Comment by Justineo** [comment]
Unfortunately Prettier doesn't seem to support configuring this.

**Comment by alexmiddeleer** [comment]
I opened this PR knowing there was a good chance it wouldn't work. Declining for now.

**Pull request closed without merging**
