### PR TITLE
Add `debug` function

### PR DESCRIPTION
**Pull request by SergiCL**
This PR contains the changes discussed in #1461 

**What kind of change does this PR introduce?** (check at least one)
- [x] Feature

**Does this PR introduce a breaking change?** (check one)
- [x] No

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch.
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/vuejs/vue-test-utils/blob/dev/.github/CONTRIBUTING.md#development-setup
- [x] New/updated tests are included

### CODE REVIEW

**Comment by lmiller1990** [comment]
Great work. I personally do not want to make the API even bigger at this point - I also think `debug` is the wrong name for this function, since it does not debug anything, it just prints html. `debug` suggests it will drop you into a kind of console debugger (like `pry` from perl/python/rub  or a JS debugger, like you get in IDEs such as WebStorm.

For this reason, I think this makes way more sense as an option to `html`. Eg: `console.log(wrapper.html({ pretty: true })`. We could also set this via a `config` variable to make this the default, is the users chooses to do so.

@afontcu @JessicaSachs @dobromir-hristov thoughts?

**Comment by dobromir-hristov** [comment]
Yeah same.

**Comment by Stoom** [comment]
It looks like the current `wrapper.html()` already pretty prints.  From the look at the code, this just does a `console.log` (which doesn't seem to be desirable) and loops through a `WrapperArray`.

**Comment by SergiCL** [comment]
I'm going close this to avoid confusion and open a new one with the changes described in #1461 when done.

**Pull request closed without merging**
