### PR TITLE
[RU] Translation ready

### PR DESCRIPTION
**Pull request by Alex-Sokolov**

### CODE REVIEW

**Comment by eddyerburgh** [comment]
Great work 🙌

@simplesmiler would you be able to review?

**Comment by Alex-Sokolov** [comment]
@eddyerburgh maybe merge now, and @simplesmiler review when he will be online?

**Comment by eddyerburgh** [comment]
It would be good to get a second pair of eyes, but since you've done a lot of translation for Vue already I'll merge without a review. Hopefully @simplesmiler will be able to review when he's back

**Comment by Alex-Sokolov** [comment]
@eddyerburgh thanks! I think users start reading and help with finding mistakes too. When it will be published?

**Comment by eddyerburgh** [comment]
Just published

**Pull request merged**
