### PR TITLE
[RU] Translation update

### PR DESCRIPTION
**Pull request by Alex-Sokolov**

### CODE REVIEW

**Comment by eddyerburgh** [comment]
We need a Russian speaker to review these changes. Do you know any speakers who could review?

**Comment by Alex-Sokolov** [comment]
I can review 😄 maybe @gbezyuk can help

**Comment by gbezyuk** [comment]
Looks good to me ;)

**Comment by eddyerburgh** [comment]
Thanks @Alex-Sokolov  and @gbezyuk 😀

**Pull request merged**
