### PR TITLE
fix: #1872 Chang the type of createLocalVue method

### PR DESCRIPTION
**Pull request by coolboy0961**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch.
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/vuejs/vue-test-utils/blob/dev/.github/CONTRIBUTING.md#development-setup
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Review by lmiller1990 — APPROVED** [review]

**Comment by coolboy0961** [comment]
@lmiller1990 

Thank you for the review.
Can you tell me about when it will be released?

**Comment by lmiller1990** [comment]
I can do a release this weekend 👍 

Please tag me if it is not released by Monday (19th July).

**Comment by coolboy0961** [comment]
@lmiller1990 
Hello, This is a reminder for the release of this pull request.

**Comment by lmiller1990** [comment]
@coolboy0961 I have release 1.2.2: https://github.com/vuejs/vue-test-utils/releases/tag/v1.2.2

**Pull request merged**
