### PR TITLE
Add sleep

### PR DESCRIPTION
**Pull request by 38elements**

### CODE REVIEW

**Comment by eddyerburgh** [comment]
Thanks for the PR, but I don't think we should add something like sleep to the library. You can start an issue and see what others think, but my opinion is that anything not related to Vue shouldn't be included in the library

**Comment by 38elements** [comment]
I think that when asynchronous processing is executed in `Promise`, it needs to sleep asynchronously.

**Comment by 38elements** [comment]
I see.
I will make issue.

**Comment by 38elements** [comment]
I think it is necessary because it is only 3 lines.

**Pull request closed without merging**
