### PR TITLE
docs: fix broken links in guides/choosing-a-test-runner (fix #805)

### LINKED ISSUE #805: docs: Broken links
### Version
1.0.0-beta.20

### Reproduction link
[https://vue-test-utils.vuejs.org/guides/#testing-single-file-components](https://vue-test-utils.vuejs.org/guides/#testing-single-file-components)

### Steps to reproduce
Open https://vue-test-utils.vuejs.org/guides/#testing-single-file-components

Try to open  in new tab this links:
- Testing SFCs with Jest
- Testing SFCs with Mocha   webpack

### What is expected?
Open docs section in new tab

### What is actually happening?
404 error

### PR DESCRIPTION
**Pull request by moraveyo**

### CODE REVIEW

**Comment by 38elements** [comment]
It seems that the links work normally now.
Would you tell me why this change is necessary?
https://vue-test-utils.vuejs.org/guides/choosing-a-test-runner.html#testing-single-file-components

**Comment by moraveyo** [comment]
Doesn't open in new tab - got 404. I filed an issue #805

**Comment by moraveyo** [comment]
These links open not really as I expect In the same window too. In fact, these are the sections of the same document: look at the navigation, and after all you can simply scroll down to them.

But when you click at the link - it opens as separate document.
A little confusing.

**Comment by moraveyo** [comment]
Some research.

When you just click the link, it opens with url:https://vue-test-utils.vuejs.org/guides/testing-SFCs-with-jest.html (see the upper case!) - the Vue works it out fine.

When you open it in new tab/window - the page first blinks like something is there, and then it's 404. And the url is all lowercase.

So maybe it's some deeper problem in Vue itself, I'm not so deep in it.

**Comment by moraveyo** [comment]
Should have written it in the issue... I'll copy there.

**Comment by eddyerburgh** [comment]
Thanks for this @moraveyo . Does the URL change solve your issue?

**Comment by moraveyo** [comment]
Yes, it does.

**Review by eddyerburgh — APPROVED** [review]

**Pull request merged**
