### PR TITLE
feat: remove deprecation warning from `isVisible` method

### PR DESCRIPTION
**Pull request by xanf**
Related issue: #1532

This PR removes deprecation from `isVisible` method since this method is expected to be available for testing `v-show` directive
Logic of method is ported from `jest-dom` implementation (obviously we can't rely on `getComputedStyle` so we do not test CSS-based visibility)

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [X] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [X] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [X] It's submitted to the `dev` branch.
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [X] All tests are passing: https://github.com/vuejs/vue-test-utils/blob/dev/.github/CONTRIBUTING.md#development-setup
- [X] New/updated tests are included

### CODE REVIEW

**Comment by afontcu** [comment]
Looks good – I guess we should update https://vue-test-utils.vuejs.org/upgrading-to-v1/#isvisible too?

**Comment by xanf** [comment]
> Looks good – I guess we should update https://vue-test-utils.vuejs.org/upgrading-to-v1/#isvisible too?

Great catch, fixed!

**Review by lmiller1990 — APPROVED** [review]

**Comment by lmiller1990** [comment]
Thank you for pushing back on these deprecations @xanf

**Comment by lmiller1990** [comment]
I will release 1.1 this weekend.

**Pull request merged**
