### PR TITLE
docs(mocha-webpack): replace mocha-webpack by mochapack fork

### PR DESCRIPTION
**Pull request by alexbonhomme**
Hey!

This PR fix current documentation about testing with webpack + mocha. 

As `mocha-webpack` seems not maintained anymore the current guide doesn't works anymore. A fork named `mochapack` fix the issue, so I fixed the doc accordingly.

### CODE REVIEW

**Comment by eddyerburgh** [comment]
Thanks for this.

Although mocha-webpack not being maintained is an issue, https://github.com/sysgears/mochapack only includes the initial commit. We won't change the recommendation until there's a proven alternative

**Comment by jblotus** [comment]
I arrived here after trying to follow the guide and use mocha-webpack. It looks like mochapack has been updated since this ticket.

**Comment by jblotus** [comment]
I can report that I was able to run vue-test-utils successfully with webpack4 and mochapack.

**Comment by nothingismagick** [comment]
The staleness of mocha-webpack was the reason why we didn't include it in @quasar/testing. Will look into this new repo and report back.

**Comment by despreston** [comment]
+1 for moving to mochapack. I went down the same route of broken tests and finally discovering mochapack.

**Comment by eddyerburgh** [comment]
OK, it's been a few months and mochpack is being actively maintained.

Can you resolve the conflicts in this PR @alexbonhomme?

**Comment by alexbonhomme** [comment]
Sure, I'll have a look on it quickly

**Comment by afontcu** [comment]
Thank you for handling this! 🎉

**Pull request merged**
