### PR TITLE
fix(validators): support components returning render function from setup (fix #1596)

### LINKED ISSUE #1596: Components only returning a render function from setup aren't considered components
### Subject of the issue

Components using the Composition API that return a render function from `setup` are not considered valid Vue Components by the internal validator. Consequently, they can’t be used as stubs.

### Steps to reproduce

Have a component using the composition API without template and where the `render` function is returned by the `setup` function:

```js
import { defineComponent, createElement } from '@vue/composition-api';

export default defineComponent({
  name: 'CFlexItem',

  setup(props, { slots }) {
    return () => {
      return createElement("div", {}, slots.default && slots.default());
    };
  },
});
```

When trying to mount it like this:

```js
import CFlex from './CFlex';
import CFlexItem from './CFlexItem';

mount(CFlex, {
  stubs: {
    CFlexItem
  },
  slots: {
    default: [
      '<CFlexItem>1</CFlexItem>',
      '<CFlexItem>2</CFlexItem>',
      '<CFlexItem>3</CFlexItem>',
    ],
  },
});
```

Vue-test-utils throws the following error:

> [vue-test-utils]: options.stub values must be passed a string or component

Theses components’ [code can be found here](https://github.com/liip/chusho/tree/master/packages/chusho/src/components/CFlex).

### Expected behaviour

Vue components using solely a render function through setup should be considered valid components.

### Possible Solution

Adapt [isVueComponent](https://github.com/vuejs/vue-test-utils/blob/dev/packages/shared/validators.js#L31-L49) method to handle this specific kind of components. But I’m not sure how this should be done, hints welcome so I can potentially submit a PR.

### PR DESCRIPTION
**Pull request by LeBenLeBen**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix. Closes #1596
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch.
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/vuejs/vue-test-utils/blob/dev/.github/CONTRIBUTING.md#development-setup
- [ ] New/updated tests are included

### CODE REVIEW

**Comment by lmiller1990** [comment]
Any chance to add a test for this?

**Comment by LeBenLeBen** [comment]
@lmiller1990 I was expecting this 😅 I didn't add tests because I didn't find any existing tests related to this method nor validators in general in the code base. I’m not sure where these should be added, could you guide me a bit?

**Comment by lmiller1990** [comment]
Sure thing, just stick in here: https://github.com/vuejs/vue-test-utils/blob/dev/test/specs/mount.spec.js. This codebase avoids testing implementation details (good thing) and just tests things however the user would be do it (usually with `mount`).

There is already a test using the composition API plugin, you could copy and paste that one. Just make a component with a `setup` function that returns a render function and assert `wrapper.html()` contains whatever the render function returns.

We are in the process of moving to Jest, but until then you need to build bundle each time you change anything in `packages`. So add you test, and run `yarn build && yarn test:unit:only` to see if it passes.

**Comment by LeBenLeBen** [comment]
@lmiller1990 Thanks for the guidance, hope that fulfill your expectations, otherwise let me know!

**Comment by lmiller1990** [comment]
@LeBenLeBen if you have some time can you try merging the latest dev to your branch?

We moved to jest, it should make it easier to fix the CI and get this merged. Sorry I didn't get back to you - I thought I had pinged you, I guess not.

Can you merge in dev and push again? Everything should be green then and we can merge.

**Comment by LeBenLeBen** [comment]
@lmiller1990 Done!

**Comment by LeBenLeBen** [comment]
I’m not sure why it doesn’t work with Vue 2.5… I tried to update `@vue/composition-api` to the latest stable but it didn’t fix it, moving to the 1.0 beta introduce other issues and I’m not sure you want to go this way.

It seems that [the oldest version supported is Vue 2.5.22](https://github.com/vuejs/composition-api/blob/v0.6.7/package.json#L71). Does the compat test use the latest 2.5 patch or 2.5.0 ?

**Comment by lmiller1990** [comment]
If you are having trouble with an older failing just add a conditional to skip it, see here for an example: https://github.com/vuejs/vue-test-utils/blob/ba8454453a063c1e105ccc04a6603cafb841df6b/test/specs/mount.spec.js#L98

Pretty keen to get this merged.

**Comment by LeBenLeBen** [comment]
@lmiller1990 🚀

**Pull request merged**
