### PR TITLE
Remove Array.prototype.includes and Array.prototype.findIndex (fix #608)

### LINKED ISSUE #608: Use of Array.prototype.includes breaks unit tests in browsers that do not support this.
### Version
1.0.0-beta.16

### Reproduction link
[https://codesandbox.io/s/7ykvrxrw0](https://codesandbox.io/s/7ykvrxrw0)

### Steps to reproduce
1. Download codesandbox codes.
2. Run tests on IE11 with karma.

### What is expected?
Tests should pass or fail, but not be terminated.

### What is actually happening?
Test is terminated due to "TypeError: Object doesn't support property or method 'includes"

---
Same as https://github.com/vuejs/vue-test-utils/issues/499 which reports use of 'Array.prototype.find'.

The specific line is:
https://github.com/vuejs/vue-test-utils/blob/v1.0.0-beta.16/packages/test-utils/src/wrapper.js#L519

Array.prototype.includes supported browsers: 
https://caniuse.com/#search=Array.prototype.includes

### PR DESCRIPTION
**Pull request by honeroku**
TODO
- [ ] make test if possible, or add eslint rule.
  - https://github.com/vuejs/vue-test-utils/issues/608#issuecomment-389076320
- [x] Run some unit test using `@vue/test-utils`

### CODE REVIEW

**Comment by lusarz** [comment]
Great finding!

**Comment by honeroku** [comment]
@eddyerburgh I investigated [eslint-plugin-compat](https://github.com/amilajack/eslint-plugin-compat) with `browserslist: ["last 1 versions", "Explorer >= 9"]` according to [vue supported browsers](https://github.com/vuejs/vue) but had no luck to pick up those `includes` and `findIndex` on dev branch.
And I have no other idea to detect browser compatibility.

Ashamed of myself but would you mind merging this PR without systematic testimony?

**Review by eddyerburgh — APPROVED** [review]
Thanks :)

**Comment by honeroku** [comment]
Thank you!!

**Comment by eddyerburgh** [comment]
The eslint-compat-plugin doesn't catch lots of unsupported features right now—https://github.com/amilajack/eslint-plugin-compat/issues/72#issuecomment-288834016

**Pull request merged**
