### PR TITLE
Update testing-async-components.md

### PR DESCRIPTION
**Pull request by ghost**
refactor: 修改一个错别字：“具柄” 改为 “句柄”

### CODE REVIEW

**Comment by legend1992** [comment]
Update testing-async-components.md

**Comment by JessicaSachs** [comment]
Thank you! 😊

**Comment by lmiller1990** [comment]
Hey @lmlife2016 , if you can merge the conflict we can merge this up! Thanks.

**Comment by JessicaSachs** [comment]
Rebased and merged in #1412

**Pull request closed without merging**
