### PR TITLE
fix(#1426): Enhance TypeScript overloads for functional components

### LINKED ISSUE #1426: Cannot write the type safe functional component test case.
### Version
1.0.0-beta.31

### Reproduction link
[https://gist.github.com/kahirokunn/a15c911cbad33082afb41cc861524c2d](https://gist.github.com/kahirokunn/a15c911cbad33082afb41cc861524c2d)

### Steps to reproduce
Just inject generics to FunctionalComponentOptions
ex: FunctionalComponentOptions<{ tag: string }>

### What is expected?
no type error

### What is actually happening?
I got type error

---
No overload matches this call.
  Overload 1 of 3, '(component: VueClass<Vue>, options?: ThisTypedShallowMountOptions<Vue>): Wrapper<Vue>', gave the following error.
    型 'FunctionalComponentOptions<{ tag: string; }, PropsDefinition<{ tag: string; }>>' の引数を型 'VueClass<Vue>' のパラメーターに割り当てることはできません。
      型 'FunctionalComponentOptions<{ tag: string; }, PropsDefinition<{ tag: string; }>>' を型 'new (...args: any[]) => Vue' に割り当てることはできません。
        型 'FunctionalComponentOptions<{ tag: string; }, PropsDefinition<{ tag: string; }>>' にはシグネチャ 'new (...args: any[]): Vue' に一致するものがありません。
  Overload 2 of 3, '(component: ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<...>>, options?: ThisTypedShallowMountOptions<...>): Wrapper<...>', gave the following error.
    型 'FunctionalComponentOptions<{ tag: string; }, PropsDefinition<{ tag: string; }>>' の引数を型 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<...>>' のパラメーターに割り当てることはできません。
      プロパティ 'props' の型に互換性がありません。
        型 'PropsDefinition<{ tag: string; }>' を型 'PropsDefinition<Record<string, any>>' に割り当てることはできません。
          型 'ArrayPropsDefinition<{ tag: string; }>' を型 'PropsDefinition<Record<string, any>>' に割り当てることはできません。
            型 'ArrayPropsDefinition<{ tag: string; }>' を型 'ArrayPropsDefinition<Record<string, any>>' に割り当てることはできません。
              Property 'tag' is missing in type 'Record<string, any>' but required in type '{ tag: string; }'.
  Overload 3 of 3, '(component: FunctionalComponentOptions<Record<string, any>, PropsDefinition<Record<string, any>>>, options?: ShallowMountOptions<Vue>): Wrapper<...>', gave the following error.
    型 'FunctionalComponentOptions<{ tag: string; }, PropsDefinition<{ tag: string; }>>' の引数を型 'FunctionalComponentOptions<Record<string, any>, PropsDefinition<Record<string, any>>>' のパラメーターに割り当てることはできません。
      型 'PropsDefinition<{ tag: string; }>' を型 'PropsDefinition<Record<string, any>>' に割り当てることはできません。
        型 'ArrayPropsDefinition<{ tag: string; }>' を型 'PropsDefinition<Record<string, any>>' に割り当てることはできません。
          型 'ArrayPropsDefinition<{ tag: string; }>' を型 'ArrayPropsDefinition<Record<string, any>>' に割り当てることはできません。ts(2769)
helloWorld.spec.ts(12, 61): 'tag' is declared here.

### PR DESCRIPTION
**Pull request by kahirokunn**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch.
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/vuejs/vue-test-utils/blob/dev/.github/CONTRIBUTING.md#development-setup
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

Closes #1426

### CODE REVIEW

**Comment by kahirokunn** [comment]
@lmiller1990 よろしくおねがいします！

**Comment by lmiller1990** [comment]
This is just typing for the props definitions, right? Can you give an example of what this actually does (eg does this give better VSCode suggestions?)

**Comment by kahirokunn** [comment]
I wrote the test code like this.
https://gist.github.com/kahirokunn/a15c911cbad33082afb41cc861524c2d

I got the error in there

```
const wrapper = shallowMount(functionalComponent, { localVue, propsData: { tag: 'p' } })
```

because functionalComponent type is not FunctionalComponentOptions<Record<any, any>>
my functionalComponent type is FunctionalComponentOptions<{ tag: string }>
FunctionalComponentOptions approve to inject Generics.
so I fixed vue test utils type definition.

**Comment by lmiller1990** [comment]
Right, makes sense. Seems fine to me. Will give it a try and merge this up tomorrow.

**Comment by kahirokunn** [comment]
Thank you!

**Comment by lmiller1990** [comment]
Forgot about this... it looks fine, let's merge it up. I am not sure when this will be released - probably during Feb sometime.

VTU for V3 will be much more TS friendly - I might ask for your help with some of the definitions 🤔

**Pull request merged**
