### PR TITLE
Feat: add callback function to trigger method

### PR DESCRIPTION
**Pull request by sqal**
Sometimes when testing our components, default Vue event modifiers may be insufficient so we need to have a way to modify event object before it gets dispatched.

### CODE REVIEW

**Comment by eddyerburgh** [comment]
What are the advantages of using a callback over an object to augment the event object?

```js
button.trigger('mousedown', (e) => {
  e.button = 0
})
```

```js
button.trigger('mousedown', {
  button: 0
})
```

**Comment by sqal** [comment]
@eddyerburgh I think if we wanted to extend the event object, we won't be able to do something like this:

`eventObject = Object.assign(eventObject, objToExtend)`

`trigger(document, 'click', { defaultPrevented: true })`

won't work, it will throw - Uncaught TypeError: Cannot assign to read only property 'defaultPrevented' of object '#<Event>'

Also, i think we should replace `new Event(event)` with `new Event(event, { bubbles: true, cancelable: true })`   because currently doing

```
triggerEvent(document, 'click', (e) => {
  e.preventDefault()
})
```

does not prevent the default action, reproduction here -> https://jsfiddle.net/z01xhwcu/

**Comment by eddyerburgh** [comment]
I think that those read only properties can't be overwritten either when edited in a callback or extending the event object. 

Just ran this test in the browser -

```js
function editEvent(cb) {
  const event = new Event('click')
  cb(event)
  console.log(event)
}

editEvent(e => e.defaultPrevented = true)
```

Does not overwrite `defaulyPrevented`.

Can you get a working example where the callback API does something that extending with an object can't do?

> Also, i think we should replace new Event(event) with new Event(event, { bubbles: true, cancelable: true }) because currently doing

Sounds good, can you make the change in this PR?

**Comment by sqal** [comment]
> I think that those read only properties can't be overwritten either when edited in a callback or extending the event object.

Correct.

> Can you get a working example where the callback API does something that extending with an object can't do?

The example with preventDefault() :) Let's say I have method in my component:

```
someMethod(event) {
  if (event.defaultPrevented) return;
  // otherwise, do something
}
```

with the callback fn you can call `e.preventDefault()` to test this method, it won't be possible without callback since you cannot override defaultPrevented value.

**Comment by eddyerburgh** [comment]
Ah yeah of course 😛 

So personally I prefer an object API over the callback API. We have more control over the input, and we can throw custom errors for common properties that are read only. 

Although the callback API you've suggested is a lot less maintenance. But I can imagine getting lots of questions about not being able to set target. We can warn that target can't be set if we use an options object

For the preventDefault() example, we could have something like this:

```js
triggerEvent(document, 'click', {
  preventDefault: true
})
```

What do you think?

**Comment by sqal** [comment]
Sure, sounds good  and i am fine with this :) So, I guess we're done with this PR and you'll implement these changes on your own?

**Comment by eddyerburgh** [comment]
You could add some more commits to this PR, or create a new one.

I won't have time to get around to this in the next few days so a PR would really be appreciated! 😄

**Comment by eddyerburgh** [comment]
I can add this tomorrow if you aren't working on it

**Comment by sqal** [comment]
I am sorry, but I will be busy at work, so go ahead and add it yourself. Thank you <3

**Comment by eddyerburgh** [comment]
closed with 6ced351ee35e8c8abb54532f90b649a220185124

Thanks for the PR 😊

**Pull request closed without merging**
