### PR TITLE
add external link for creating new issues

### PR DESCRIPTION
**Pull request by phiter**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [x] Other, please describe: github project organization

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch.
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/vuejs/vue-test-utils/blob/dev/.github/CONTRIBUTING.md#development-setup
- [ ] New/updated tests are included

**Other information:**

Since this project only allows new issues to be created through vue issue helper, I suggest we use [Github's template chooser](https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser) which enables a configuration of contact links and disabling the issue creation interface.

You can see how it looks in the Vuetify repository. Click in "new issue" here:

https://github.com/vuetifyjs/vuetify/issues

### CODE REVIEW

**Comment by afontcu** [comment]
Hi! [Vue issue helper](https://new-issue.vuejs.org/?repo=vuejs/vue-test-utils) actually supports Vue Test Utils, doesn't it?

image

**Comment by phiter** [comment]
Yeah it does, the contact link will send you to this page.

**Comment by afontcu** [comment]
oh okay I see now, this sentence kind of mislead me ^^ "Since this project does not allow new issues to be created through vue issue helper"

**Review by afontcu — APPROVED** [review]
I'm okay with this, I'm gonna wait until other team members share their opinion 👍

**Comment by phiter** [comment]
@afontcu oh my bad I probably started typing something else and changed my mind and typed this lol, fixed it.

**Comment by lmiller1990** [comment]
Do we need this?

I would be happy to just let people make issues here in GH. No-one likes complicated issue templates.

Only thing I'd like to do is include a link to a sandbox for easy reproductions.

**Comment by lmiller1990** [comment]
What do you guys think about dropping the complicated form and just having a super basic text template with

- What is the problem
- Repro link if relevant
- Proposed solution?

**Comment by phiter** [comment]
@lmiller1990 I like this idea. Custom issue creators are sometimes a burden and I've given up writing issues sometimes because of them. Even though I understand why they can be useful, I think it can be too bureaucratic.

So yeah I'm definitely in favor of adding new issue templates, like they did for [this repo for example](https://github.com/ResultadosDigitais/matrix/issues/new/choose).

**Comment by lmiller1990** [comment]
Didn't know this was a feature!

Would you like to make a PR for this @phiter ?

**Comment by phiter** [comment]
@lmiller1990 Yeah I can do it. Should we follow the same templates as them?

**Comment by lmiller1990** [comment]
@phiter Sure, those seem reasonable!

**Comment by lmiller1990** [comment]
solved in #1563

**Comment by lmiller1990** [comment]
Just tried it out this is a huge improvement @phiter thanks a lot.

**Pull request closed without merging**
