### PR TITLE
fix: set wrapper.vm if the element binds Vue instance

### PR DESCRIPTION
**Pull request by 38elements**
This is related to #687.

### CODE REVIEW

**Comment by eddyerburgh** [comment]
Can you check in createWrapper if there is a componentInstance, and if there is return a wrapper using componentInstance?

```
export default function createWrapper (
  node: VNode | Component,
  options: WrapperOptions
) {
  if (node.componentInstance) {
    return new VueWrapper(node.componentInstance, options)
  }
  return node instanceof Vue
    ? new VueWrapper(node, options)
    : new Wrapper(node, options)
}
```

**Comment by 38elements** [comment]
Thank you for reviewing.
I changed it.

**Comment by eddyerburgh** [comment]
If that works then I think you can remove the extra code in this PR?

**Comment by 38elements** [comment]
No, it is not.
I think that it is necessary to get a component instance from `vm.$children`.

**Comment by 38elements** [comment]
I think that the following code is not necessary if this change code exists. 

```js
  if (node.componentInstance) {
    return new VueWrapper(node.componentInstance, options)
  }
```

**Comment by eddyerburgh** [comment]
Why is it necessary to get the instance from vm.$children?

I thought we could keep the same logic for getting vnodes. Then we could check that if the vnode is for a component instance in the create-wrapper function.

**Comment by 38elements** [comment]
I misunderstood.
This passed at 2.5.
I will fix it.

**Comment by 38elements** [comment]
I fixed it.
`VNode.child` was changed to `VNode.componentInstance` at `2.1.9`.
https://github.com/vuejs/vue/commit/ced2dfc8f704b07cd59467eca38c58c590d0c012

**Review by eddyerburgh — APPROVED** [review]

**Pull request merged**
