### PR TITLE
Adding missing documentation

### PR DESCRIPTION
**Pull request by vegerot**
When reading through the documentation I was very confused why it randomly started talking about `setTimeout`, when I realized it was referring to a hypothetical `setTimeout` example that wasn't there.

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [x ] Other, please describe: Documentation

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x ] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x ] It's submitted to the `dev` branch.
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ x] All tests are passing: https://github.com/vuejs/vue-test-utils/blob/dev/.github/CONTRIBUTING.md#development-setup
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by lmiller1990** [comment]
Thanks for the contribution. I agree the docs are not very good.

I'm not sure our docs should go this in depth anyway. Should we just delete the `setTimeout` example, and all mentions to it? I don't think anyone is actually writing tests like this, it bleeds implementations details into your specs.

Can we just simplify this to explain to use `await flushPromises` to ensure the DOM is updated or something?

We will redo docs entirely for Vue 3 integration main for this reason - they are way too complicated.

**Comment by lmiller1990** [comment]
@vegerot still interested to get this merged? I think we should try and make it a bit more concise.

**Comment by vegerot** [comment]
I’ve always been interested in merging this 🙂

**Comment by lmiller1990** [comment]
@vegerot can we simply the explanation? I don't think the docs for a test runner is the right place to explain the complexities of the event loop. It think we already have way too much information that is not about testing. 

We could include something more simple like "This problem occurs because Vue updates the DOM asynchronously, and the test runner executes assertions synchronously. Work around this by running `await wrapper.vm.$nextTick` to ensure the DOM is updated before the assertion runs. See <this external link> for more information".

I don't think `setTimeout` is something we should encourage or mention. While this does work, it's not very explicit or clear why it does, unless you know the event loop very well. `nextTick` is definitely more clear. It would be great if we could just have "one way" of doing things.

**Comment by vegerot** [comment]
Yeah, that makes sense.  I'll try that out

**Pull request closed without merging**
