### PR TITLE
fix: improve scopedSlots option

### LINKED ISSUE #706: Tests for default scopedSlots not mounting
### Version
1.0.0-beta.18

### Reproduction link
[https://codesandbox.io/s/0mrvjmvk6l](https://codesandbox.io/s/0mrvjmvk6l)

### Steps to reproduce
Hi there, so I’m building a library for work and I’m using the render function and only accepting default scoped slots. I have the render function currently defined as

```
  render() {
      return this.$scopedSlots.default({ ...this.computedStateAndHelpers })
  },
```

When I try to write tests for it (using jest) I always get an error when trying to mount the component

```
const wrapper = shallowMount(Component, {
    scopedSlots: {
        default: () => '<p></p>'
    }
})
expect(wrapper.isVueInstance()).toBe(true)
expect(wrapper.name()).toBe('component-name')
```

I also tried

```
const wrapper = shallowMount(Component, {
    scopedSlots: {
        default: '<p></p>'
    }
})
expect(wrapper.isVueInstance()).toBe(true)
expect(wrapper.name()).toBe('component-name')
```

The error is

```
scopedSlots[key].trim is not a function
```

I don't know what I'm doing wrong, can someone please help me figure this out?

### What is expected?
Expecting the test to pass

### What is actually happening?
The error is

```
scopedSlots[key].trim is not a function
```

### PR DESCRIPTION
**Pull request by 38elements**
This resolves #706.

### CODE REVIEW

**Review by eddyerburgh — CHANGES_REQUESTED** [review]
Looks great! One small change. Can you rename the function to `createScopedSlots`, to be in line with createComponentStubs, createSlotVNodes, etc?

**Comment by 38elements** [comment]
Thank you for reviewing.
I renamed `getScopedSlots` to `createScopedSlots`.

**Comment by eddyerburgh** [comment]
Thanks for making the changes.

Can you also add a test case for the example in the issue:

```js
scopedSlots: {
  foo: (createElement, props) => { return createElement('div', props); },
},
```

**Comment by 38elements** [comment]
The case does not work.
I think the feature is not necessary.
I think it is not necessary to use `createElement()` to make `scopedSlots`.
`slots` mounting option is not support it.
Would you please tell me why this feature is necessary?

**Comment by 38elements** [comment]
`scopedSlotFn()` receives only `props`.

```js
nodes = scopedSlotFn(props) || fallback
```

https://github.com/vuejs/vue/blob/5a9da95b8a865416f082952a48416ffc091e4078/src/core/instance/render-helpers/render-slot.js#L27

**Comment by 38elements** [comment]
`scopedSlotFn()` receives only `props`.

```js
nodes = scopedSlotFn(props) || fallback
```

https://github.com/vuejs/vue/blob/5a9da95b8a865416f082952a48416ffc091e4078/src/core/instance/render-helpers/render-slot.js#L27


If you think the feature is necessary, I will add an API as below.

```js
scopedSlots: {
  default: (createElement) => (props) => { return createElement('div', props); }
}
```

**Comment by eddyerburgh** [comment]
Ok, I agree that the API does not look good. I'll merge the branch as it is 👍

**Review by eddyerburgh — APPROVED** [review]

**Comment by 38elements** [comment]
Thanks.

**Comment by 38elements** [comment]
#657 is not closed.
I want to confirm.
Do you think this API is necessary?

```js
scopedSlots: {
  default: (createElement) => (props) => { return createElement('div', props); }
}
```

**Comment by eddyerburgh** [comment]
Not currently, but it's a feature request so we should keep it open until we've decided definitively. 

I also haven't had enough time to fully assess the scopedSlots and slots API

**Comment by 38elements** [comment]
Thank you for reply.
I think that it is better to remove `intend to impliment` label for #657.

**Comment by kayandra** [comment]
@38elements thank you for this

**Pull request merged**
