### PR TITLE
Update props.md. Text correction

### PR DESCRIPTION
**Pull request by WhoisUnknown**

### CODE REVIEW

**Comment by kazupon** [comment]
@Alex-Sokolov 
Could you review about it, please? 🙏

**Comment by WhoisUnknown** [comment]
> @Alex-Sokolov
> Could you review about it, please?

This is a missprint

**Review by Alex-Sokolov — APPROVED** [review]

**Comment by Alex-Sokolov** [comment]
@kazupon done)
@WhoisUnknown thanks for PR!

**Review by kazupon — APPROVED** [review]

**Comment by kazupon** [comment]
Thanks!

**Pull request merged**
