### PR TITLE
fix: reconcile the overridden prototype of component with _Vue mixins

### PR DESCRIPTION
**Pull request by kuitos**
refer to https://github.com/vuejs/vue-test-utils/pull/856

### CODE REVIEW

**Comment by kuitos** [comment]
@eddyerburgh could you donate some time to review it?

**Review by eddyerburgh — APPROVED** [review]
Good solution, thanks :)

**Comment by eddyerburgh** [comment]
I had to revert this change again before the release. It was causing issues with this new test—https://github.com/vuejs/vue-test-utils/blob/dev/test/specs/mounting-options/localVue.spec.js#L68.


The problem with modifying the prototype chain, or the super chain ourselves is that it's very difficult to plan for edge cases. So I think the solution would be to provide an option to not extend the component, although that would mean stubs and mocks won't be applied.

If you have other suggested workaround I'll take a look.

**Comment by kuitos** [comment]
I had tried to change the root prototype of vue component:
```js
function getRootProto (obj) {
    if (Object.getPrototypeOf(obj) === Vue.prototype) {
      return obj
    }
    return getRootProto(Object.getPrototypeOf(obj))
}

function getExtendedComponent(component, instanceOptions) {
  const extendedComponent = component.extend(instanceOptions)
  const root = getRootProto(extendedComponent.prototype)
  Object.setPrototypeOf(root, _Vue.prototype)
  return extendedComponent
}

const Constructor = typeof component === 'function'
    ? getExtendedComponent(component, instanceOptions)
    : _Vue.extend(component).extend(instanceOptions)
```

I think I'm in the right direction, but the unit test what you added still failed.
I need to check what made it failed.

**Pull request merged**
