### PR TITLE
WIP: Migrate to jest

### LINKED ISSUE #1585: Bump deps, move to Jest, rollup 2
### Cleanup

**What should be cleaned up or changed**:

Working on V2 with Jest provides an incredibly fast feedback loop - it's a pleasure, I love working on it. Working on this is pretty slow at times, need to run `yarn build` to rebuild the bundle, and mocha-webpack just provides a less nice developer experience. Rollup v1 is also very old at this point.

To make the codebase maintainable for years to come, and more enjoyable to work on (thus more motivation to fix bugs) I would like to:

1. move to Jest
2. upgrade to rollup v2
3. bump dependencies in general

**Provide any links for context**:

### PR DESCRIPTION
**Pull request by lmiller1990**
Got Jest mostly working, just going through and updating the tests.

resolves #1585 

Edit 9 July: I am still working on this, might be a little bit longer. Rollup migration may have to wait, for now I will just focus on getting us on Jest.

### CODE REVIEW

**Comment by dobromir-hristov** [comment]
Damn, good job.
How will we run this in a browser env? I think we had such a test, could be wrong.

**Comment by lmiller1990** [comment]
Still WIP. 

For the browser, we used Karma. We can consider the "newer" combo of Jest + puppeteer. We should also look to use that in VTU v2 (currently no browser tests).

**Comment by lmiller1990** [comment]
Update... all files in `test/specs` passing with Jest! Took a while... but worth it.

Next is figure out how to run these in a browser (previously karma, still an option) and consider running the tests using the src instead of the built files (but have both in the CI run).

**Comment by lmiller1990** [comment]
closed in favor of  https://github.com/vuejs/vue-test-utils/pull/1629

**Pull request closed without merging**
