### PR TITLE
Sync mode cleanup

### PR DESCRIPTION
**Pull request by AtofStryker**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [ ] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `dev` branch.
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] All tests are passing: https://github.com/vuejs/vue-test-utils/blob/dev/.github/CONTRIBUTING.md#development-setup
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Review by lmiller1990 — APPROVED** [review]
This is still "draft". do you intend to add something else?

The changes seem pretty standard... no problem here.

**Comment by AtofStryker** [comment]
@lmiller1990 I actually forgot about this 😆 .  I will likely do another audit of this but I think these changes were the bulk of it. Is there anything in particular we should be looking at when cleaning up sync mode?

**Comment by lmiller1990** [comment]
@AtofStryker no idea - I think most of the sync mode stuff is gone now, I haven't thought about it in a long time.

We could just merge this up now and then I could do a release with your new config handle feature and whatever else has bee merged in lately. what do you think?

**Comment by AtofStryker** [comment]
@lmiller1990 Sounds like a solid plan to me! If I find anything missed while cleaning up, opening another PR is always an option 🙂

**Pull request merged**
