### PR TITLE
fix: add support for vue.extended components + add test

### PR DESCRIPTION
**Pull request by feedthejim**
Hi,

Here's the PR. I haven't had time to do much testing. 

Cheers :)

### CODE REVIEW

**Comment by eddyerburgh** [comment]
We run compatibility tests (npm run test:compatibility) against each major version of Vue, and the test you added failed on version 2.0.8

**Comment by feedthejim** [comment]
Ok @eddyerburgh after investigating, this.$props came only after Vue 2.2.1, so i fixed my test

**Comment by feedthejim** [comment]
@eddyerburgh when are you planning a new release ?

**Comment by eddyerburgh** [comment]
I'll release on Sunday, I'm away from my laptop until then unfortunately

**Pull request merged**
