### PR TITLE
Fix wrapper.attributes() method

### PR DESCRIPTION
**Pull request by tianyong90**
#263

### CODE REVIEW

**Comment by tianyong90** [comment]
Sure, I am starting working on it. 😄

**Comment by tianyong90** [comment]
@eddyerburgh Hi, after reviewing the tests, I found that these needed unit tests are already exists and there's no need to change them，none of them failed.
image

**Comment by eddyerburgh** [comment]
Hi @tianyong90 . These are bad tests if they passed when the code was buggy. Would you like to investigate why they were passing when the code was returning undefined? If not, I can merge and investigate myself. Thanks for the PR 😀

**Comment by tianyong90** [comment]
image

Aha, Finally found out that it seems that it's a bug in the `dist` but not in `src`, perhaps there's something wrong with the bounding tools or configuration. Just like shown in the picture above, the spread operator is transformed to `[].concat()`, this is the reason why unit tests all passed, but broken in my actual use.
To fix it, you can just merge the PR, or make some change with the building process.

**Comment by eddyerburgh** [comment]
Great find, thanks for the PR 🙂

**Pull request merged**
