### PR TITLE
docs: modify the wrong Chinese word

### PR DESCRIPTION
**Pull request by whyer11**
"阀值" is a wrong word in Chinese, "阈值" should be used here

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [x] Other, please describe: documents

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch.
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/vuejs/vue-test-utils/blob/dev/.github/CONTRIBUTING.md#development-setup
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by whyer11** [comment]
why checks all run failed?

image

**Comment by lmiller1990** [comment]
I guess we need to update the Netlify infrastructure. I have no idea how to do this, I will find out. Maybe @afontcu has some context 🤔 ?

**Comment by whyer11** [comment]
any update?

**Comment by lmiller1990** [comment]
I do not have access to the Netlify account to update the image, but I asked someone who does. Should be able to get this fixed this week.

**Comment by lmiller1990** [comment]
Still no luck. I miss GH pages, it was a lot easier that having to manage access to multiple tools. Maybe we should move back to that.

**Comment by lmiller1990** [comment]
Gonna merge this while I try to chase up a Netlify fix.

**Pull request merged**
