### PR TITLE
build(rollup): upgrade rollup from 1.x to 2.x

### PR DESCRIPTION
**Pull request by AtofStryker**
Upgrade rollup and susequent dependencies from 1.x to 2.x

Previously discussed in https://github.com/vuejs/vue-test-utils/pull/1629#issuecomment-668925267. To summarize:

The upgrade from Rollup 1.x to 2.x isn't super involved and is handled in this PR

A [gist](https://gist.github.com/AtofStryker/fbf3855b8ab43a1887aae004f0fed247#file-server-test-utils-diff) of the bundle diff is available for the team/community review. None of the semver or acorn variables are actually used in the current bundle, and the other changes can be explained by https://github.com/rollup/plugins/blame/master/packages/commonjs/src/helpers.js#L38 and https://github.com/rollup/plugins/blob/master/packages/commonjs/src/helpers.js#L58 / rollup/plugins#206. 

Even though a regression is unlikely, we should test the build and check for regressions, and I would recommend a minor release just in the rare case we would need to patch.

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [x] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch.
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/vuejs/vue-test-utils/blob/dev/.github/CONTRIBUTING.md#development-setup
- [x] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by lmiller1990** [comment]
Oops, conflicts. I guess we will review/merge these one by one to avoid this problem.

thank you!

**Comment by AtofStryker** [comment]
@lmiller1990 glad to help! I have a feeling the `yarn.lock` is going to cause conflicts on each merge into `dev`. I can just rebase them as we merge/review! This should be ready to go now.

**Comment by AtofStryker** [comment]
@lmiller1990 another rebase :laughing:

**Comment by lmiller1990** [comment]
Seems legit

**Pull request merged**
