### PR TITLE
Feat: add support for rendering named slots (#887)

### PR DESCRIPTION
**Pull request by ferm10n**

### CODE REVIEW

**Review by lmiller1990 — COMMENTED** [review]
Any chance you can add a unit test? If not I might be able to do it. Didn't realize named slots wasn't supported.

**Comment by ferm10n** [comment]
I plan on it, just haven't had the time to focus on it yet. #887 was closed too so my PR might not be needed. I'll check tomorrow

**Comment by ferm10n** [comment]
So it looks like e604f1c fixes this. I like that solution a lot better than mine lol, so I'm closing.
However there seems to be some trouble when using following the example on  https://vuejs.org/v2/guide/components-slots.html#Named-Slots, which uses the template element for named slots.

JSDOM does not serialize template contents, in accordance with the [spec](https://html.spec.whatwg.org/multipage/scripting.html#the-template-element). 

@eddyerburgh do you have any input on this, with regards to handling template elements?

**Comment by eddyerburgh** [comment]
Can you give me an example in code of the problem, and raise a new issue so I can track it

**Comment by ferm10n** [comment]
https://codesandbox.io/s/p4mmxj9mx (Learning how to use this tool, I didn't know how to pull in the latest version that is on the dev branch here)

I'm not entirely sure what should happen here to be honest, but I do imagine that it shouldn't be blank.

[Here's](https://github.com/inikulin/parse5/blob/master/packages/parse5/lib/serializer/index.js#L91) the reason why you'd get `<template></template>`. I misspoke earlier, parse5 is the cause, which is used by JSDOM.

**Pull request closed without merging**
