### PR TITLE
feat(stubs): render function props deterministically, fix #975 

### LINKED ISSUE #975: Function properties in stubs should not render source code
### Version
1.0.0-beta.25

### Reproduction link
[https://codesandbox.io/s/135my5kk9j](https://codesandbox.io/s/135my5kk9j)

### Steps to reproduce
1. Go to the Tests tabs and run the test
2. Check the Console output in the Console tab

### What is expected?
wrapper.html() should return something like
```
<childcomponent-stub clickhandler="[Function]"></childcomponent-stub> 
```

### What is actually happening?
```
<childcomponent-stub clickhandler="function bound handleClick() {
    [native code]
}"></childcomponent-stub> 
```

---
I ran into the bug because the snapshot tests failed on our CI environment, even though I had properly updates the snapshots locally. The failing spot was a Function property which was rendered differently on local and CI environments (due to Istanbuls coverage comments being added).

### PR DESCRIPTION
**Pull request by MitchLillie**
Since @briwa 's [PR](https://github.com/vuejs/vue-test-utils/pull/1237) languished and we haven't heard from them, I'm re-opening the same. Tests are working fine for me.

Closes #975 and #1209.

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [x] Yes
- [ ] No

If yes, please describe the impact and migration path for existing applications:

Applications with shallow mounted snapshot testing of components that pass functions to child components should update their snapshots.

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch.
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/vuejs/vue-test-utils/blob/dev/.github/CONTRIBUTING.md#development-setup
- [x] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Review by lmiller1990 — APPROVED** [review]
Code seems fine, but isn't this a *major* breaking change for shallow mounted snapshots? I am kind of surprised you didn't have to change other tests asserting against `wrapper.html()`.

I could be missing something - it's been a while since I touched this part of the code base.

**Comment by MitchLillie** [comment]
Yes, that's true. This will break any shallow mounted snapshots that pass a function to a child property. So definitely a breaking change, but in our repo with 2601 tests, only four had this problem. If you look at the linked issues, most folks are simply skipping testing or coverage on these problem areas, because the snapshots are completely non-deterministic between environments.

**Comment by lmiller1990** [comment]
Alright, good to know. The next release will be a minor (1.2.0) release in this case. I'll try to do it this week. Thanks!

**Comment by lmiller1990** [comment]
@MitchLillie it's out. Can you give it a test in your prod code base and let me know if we missed anything, or you have any unexpected breakages?

**Comment by MitchLillie** [comment]
@lmiller1990 Just tested, looks good on our end. We had 7 total snapshots that needed updating, out of 39 total. That's more than the original 4 because 3 were referencing mocked functions, which were already ignored in test coverage, so didn't have this issue.

**Comment by pazderka** [comment]
It has resolved most issues that i have had with rendering snapshots deterministically, however i have still 1 failing scenario (i am using Vuetify) for 1.2.0 version.

The html of the component that it fails to render deterministically is actually my custom component DatePickerMenu, which is a wrapper for vuetify DatePicker.

The problem is related with vuetify DatePicker property 'allowed_dates' which then in snapshot tests produce incorrect results, the errors look like this, for instance:

`
                <div
                  allowed_dates="() => {
                  /* istanbul ignore next */
    -             cov_1o1cojjd49().f[12]++;
    -             cov_1o1cojjd49().s[34]++;
    +             cov_kawvohiv4().f[12]++;
    +             cov_kawvohiv4().s[34]++;
                  return true;
                }"
                  class="DatePickerMenu-stub"
                  label="common:created_from"
                />
`

Implementation of DatePickerMenu looks like this:

`
    <VMenu
        v-model="show_menu"
        :close-on-content-click="true"
        transition="scale-transition"
        offset-y
        max-width="290px"
        min-width="290px"
    >
        <template v-slot:activator="{ on, attrs }">
            <VTextField
                hide-details="auto"
                :value="value_locale"
                :label="label"
                prepend-icon="mdi-calendar"
                outlined
                readonly
                :name="name"
                v-bind="attrs"
                :rules="rules"
                :class="inner_class"
                v-on="on"
            />
        </template>
        <VDatePicker
            :value="value"
            no-title
            :allowed-dates="allowed_dates"
            @change="update_value($event)"
        >
            <VContainer>
                <slot name="date-picker-append"/>
                <VRow>
                    <VCol cols="12" class="text-right">
                        <VBtn
                            text
                            color="primary"
                            @click="clear()"
                        >
                            Clear
                        </VBtn>
                    </VCol>
                </VRow>
            </VContainer>
        </VDatePicker>
    </VMenu>

`

Usage of DatePickerMenu looks like this:

`
<VCol class="pt-2 align-self-center" cols="12" sm="4" lg="2">
     <DatePickerMenu
          :value.sync="created_to"
          :allowed_dates="allowed_dates_to"
          :label="$t('common:created_to')"
      />
</VCol>
`

My snapshot tests look like this:

`
    test('empty matches snapshot', async() => {
        const options = {
            stubs: {
                'DatePickerMenu': DatePickerMenuStub,
            },
            mocks: {
                $notify: jest.fn(),
            },
        }

        wrapper = initWrapper(MessageList, options)

        await flushPromises()
        expect(wrapper.element).toMatchSnapshot()
    })
`
`
    test('messages matches snapshot', async() => {
        const options = {
            data() {
                return {
                    results_loading: true,
                }
            },
            propsData: {
                init_recipients: ['recipient@example.com'],
                init_types: ['warning'],
            },
            stubs: {
                'DatePickerMenu': DatePickerMenuStub,
            },
            mocks: {
                $notify: jest.fn(),
            },
        }

        wrapper = initWrapper(MessageList, options)

        await flushPromises()
        expect(wrapper.element).toMatchSnapshot()
    })
`

**Comment by pazderka** [comment]
Version 1.2.0 has resolved most of the issues that i have had with rendering snapshots deterministically, however i have still one failing scenario. 

I am using Vuetify and the snapshot test fails for the prop `allowed-dates` which Vuetify DatePicker exposes. This prop seems to produce unexpected results in snapshot tests, the failure looks like this, for example:

```
                <div
                  allowed_dates="() => {
                  /* istanbul ignore next */
    -             cov_1o1cojjd49().f[12]++;
    -             cov_1o1cojjd49().s[34]++;
    +             cov_kawvohiv4().f[12]++;
    +             cov_kawvohiv4().s[34]++;
                  return true;
                }"
                  class="DatePickerMenu-stub"
                  label="common:created_from"
                />
```

Any ideas how to get this to work?

**Comment by lmiller1990** [comment]
I am not sure why coverage is even showing up in the snapshots. My guess is this needs to be explored in vue-jest probably - not sure there is something to be done here 🤔 

I have not much experience with code coverage, but happy to help investigate if you are interested in doing so. Can you reproduce this easily with a fresh Vue cli project + some config?

**Pull request merged**
