### PR TITLE
add isVisible typos and missing tests

### PR DESCRIPTION
**Pull request by saintplay**
note that **isVisible.TODO.js** file

### CODE REVIEW

**Comment by eddyerburgh** [comment]
Are you planning on adding isVisible.TODO in this PR?

**Comment by saintplay** [comment]
yes!, if you allow me :)

**Comment by eddyerburgh** [comment]
Yes definitely 😄

**Comment by saintplay** [comment]
done

**Review by eddyerburgh — APPROVED** [review]
Thanks 😀

**Pull request merged**
