### PR TITLE
fix(setData): allow empty objects to be set fix #1704

### LINKED ISSUE #1704: setData with an empty object doesn't get set
### Subject of the issue

If you call `wrapper.setData({ someKey: {} })`, it doesn't set the `someKey` to `{}`

### Steps to reproduce

this test doesn't pass

```
const wrapper = mount({
  data() {
    return {
      someKey: { someValue: true },
    };
  },
  render(h) {
    return h('span');
  },
});

expect(wrapper.vm.$data).toEqual({ someKey: { someValue: true } });

wrapper.setData({ someKey: {} });

expect(wrapper.vm.$data).toEqual({ someKey: {} });
```

### Expected behaviour

This test passes

### Actual behaviour

The test doesn't pass, it still has the previous 

### Possible Solution

In here: https://github.com/vuejs/vue-test-utils/blob/dev/packages/test-utils/src/recursively-set-data.js I think it might make sense to see if the object has keys at all, if it doesn't have keys, you could set the value.

### PR DESCRIPTION
**Pull request by Haroenv**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [x] Yes
- [ ] No

If yes, please describe the impact and migration path for existing applications:

if someone relied on empty objects not updating, that now no longer makes sense

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch.
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] All tests are passing: https://github.com/vuejs/vue-test-utils/blob/dev/.github/CONTRIBUTING.md#development-setup
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

This is a tentative fix to show one possible solution, I can clean it up if you think it makes sense

### CODE REVIEW

**Comment by lmiller1990** [comment]
Seems like some tests are failing. LMK if I can help out with anything.

**Comment by Haroenv** [comment]
I didn't update the tests yet, but I'm more wondering if my approach makes sense, and whether this is a problem that should even be fixed @lmiller1990 :)

**Comment by lmiller1990** [comment]
I guess so, if Vue supports this (which it does, right, settings something in data to `{}` will not lose reactivity), it seems like VTU probably should too.

**Comment by Haroenv** [comment]
Tests are passing now, although I didn't add a new test for this yet :)

**Comment by lmiller1990** [comment]
Great. Can you add a test for this, too? Then we can merge it.

**Comment by Haroenv** [comment]
voilà @lmiller1990, new test added :)

**Review by afontcu — APPROVED** [review]
🎉

**Comment by Haroenv** [comment]
Thanks for your reactivity all 👍

**Pull request merged**
