### PR TITLE
Support for classes inspection

### PR DESCRIPTION
**Pull request by tim-hutchinson**
This PR has an implementation for #139 . I based the structure on the existing `html` and `text` methods that only work on a single instance, not an array.

Classes has a few tricky edge cases with CSS Modules. I don't use them in my own projects, so I don't have expertise on the right expected behavior, and couldn't find an official inverse function for them. With a CSS Module class that composes another class, both classes end up on the output. Right now, I'm returning both the extension and base classes back, but I don't know if this is the expected behavior. I'm also assuming that the base will always be defined in `$style`, but I haven't experience more exotic examples of CSS Modules (ie extending globals, etc).

### CODE REVIEW

**Comment by eddyerburgh** [comment]
Thanks @tim-hutchinson . I'd like to wait for some more feedback before we merge, but let's keep this open, and I'll merge once we've decided.

**Comment by eddyerburgh** [comment]
Would you be able to add `attributes` and `props` to this PR?

**Comment by tim-hutchinson** [comment]
Sure, I'll get them added.

I noticed before there are tests for `WrapperArray` in both `test/unit/specs/mount/WrapperArray` and `test/unit/specs/wrappers/wrapper-array.spec.js`. Do you prefer tests in both locations or just one?

**Comment by eddyerburgh** [comment]
Prefer tests in both locations

**Comment by tim-hutchinson** [comment]
One question on the spec for `props`. If there are no props, should it return `undefined` or `{ }`? The component itself actually has it undefined, but an empty object/array is the behavior on the other inspection functions.

**Comment by eddyerburgh** [comment]
@tim-hutchinson can you fix the merge conflict?

**Comment by eddyerburgh** [comment]
Thanks @tim-hutchinson 😀

I'll add deprecation notices to hasClass, hasProp, and hasAttribute, and release later this week

**Pull request merged**
