### PR TITLE
Respect provide from parentComponent

### LINKED ISSUE #1262: parentComponent does not provide values
### Version
1.0.0-beta.29

### Reproduction link
[https://gist.github.com/dmattia/5b99dc2584ec8241f84b30b5476b6ff3](https://gist.github.com/dmattia/5b99dc2584ec8241f84b30b5476b6ff3)

### Steps to reproduce
Run the linked test. The first two tests pass as expected, but the third test fails because: `Injection "val" not found`

### What is expected?
I would expect that using a parentComponent would inject data to the component being mounted.

### What is actually happening?
The only injected values to the child component are those that are passed explicitly through the `provide` option during mounting.

### PR DESCRIPTION
**Pull request by xanf**
Instead of replacing `parentComponent` provide - merge it, so we can `provide` values in parentComponent section of config

Fixes #1262

### CODE REVIEW

**Comment by JessicaSachs** [comment]
Hey @xanf, thanks for picking up another PR 💯. Unfortunately, the 3-4 of the specs are currently failing. Do you have time to take a look at the branch and work through the error message? Cheers.

**Comment by xanf** [comment]
@JessicaSachs Sure, I'll update this one this week

**Comment by afontcu** [comment]
Hi @xanf! any chance you could take a look at this? :)

**Comment by jdmerinor** [comment]
I'm facing this same issue :( Is there any progress with this guy?

**Comment by lmiller1990** [comment]
I don't thnk so. @jdmerinor are you interested in picking this one up by any chance? I have a bunch of other things I need to work (v3 integration, v1 release...)

**Comment by lmiller1990** [comment]
Everything is passing locally for me 🤔 

I will resolve the conflicts and run the test on CI again.

**Comment by lmiller1990** [comment]
Ok, code is fine - just one of the older versions of Vue has some compat issues with 2.1x. For some reason this is breaking `setMethods` on shallowMount in 2.1... wtf?

https://github.com/vuejs/vue-test-utils/blob/a4cbe93b9b61cf6e5bf0cf4878649fe87b5580be/test/specs/wrapper/setMethods.spec.js#L22 fails ONLY only for Vue 2.1 - seems no have no relation to the code changes here though?

**Comment by lmiller1990** [comment]
Ok this is the culprit:

https://github.com/vuejs/vue-test-utils/pull/1301/files#diff-5ff1a4e52323a0203bce1f2f3d29b110R48

**Comment by lmiller1990** [comment]
Ok so oddly enough this

https://github.com/vuejs/vue-test-utils/pull/1301/files#diff-5ff1a4e52323a0203bce1f2f3d29b110R50

is the problem 🤔

**Comment by lmiller1990** [comment]
Passing!

Thanks for the contribution @xanf !

**Review by lmiller1990 — APPROVED** [review]

**Pull request merged**
