### PR TITLE
test: demonstrate setProps bug through computed and created (#738)

### PR DESCRIPTION
**Pull request by agriffis**

### CODE REVIEW

**Comment by eddyerburgh** [comment]
Thanks for the bug repro!

This is a bug with the synchronous implementation that changed in beta.16 (https://github.com/vuejs/vue-test-utils/issues/676).

This is a very serious issue that I'm focussed on fixing.

The solution at the moment (and possibly the long term solution) is to run the tests without sync mode:
```js
it('sets component prop referenced through computed and created', () => {
  const wrapper = mountingMethod(ComponentWithComputedCreated, {propsData: {prop1: 1}, sync: false})
  wrapper.setProps({prop1: 2})
  setTimeout(() => {
    expect(wrapper.vm.prop1).to.equal(2)
  })
}) 
```

**Comment by agriffis** [comment]
@eddyerburgh Just for kicks, I rebased this to latest and it's great to see it works!

**Comment by leifriksheim** [comment]
In my case using `setTimeout` will make all test pass, even if they shouldn't

**Comment by eddyerburgh** [comment]
This should be fixed in beta.29

**Pull request closed without merging**
