### PR TITLE
fix Wrapper type definition

### PR DESCRIPTION
**Pull request by DevAnouar-FT**
Added the getComponent() function typing

**What kind of change does this PR introduce?** (check at least one)

- [ x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x ] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x ] It's submitted to the `dev` branch.
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ x] All tests are passing: https://github.com/vuejs/vue-test-utils/blob/dev/.github/CONTRIBUTING.md#development-setup
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [ x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Review by lmiller1990 — APPROVED** [review]

**Comment by lmiller1990** [comment]
Thanks!

**Comment by DevAnouar-FT** [comment]
> Thanks!

You're welcome!

**Comment by lmiller1990** [comment]
I can release this weekend 👍

**Comment by DevAnouar-FT** [comment]
> I can release this weekend

Great news! That would be awesome to get rid of augmenting the Wrapper type, at work starting from next week, just for this. Thank you in advance for the release :+1:

**Comment by lmiller1990** [comment]
Awesome... if you can consider Vue 3 + Test Utils V2 - written in TS. no type problems!

**Comment by DevAnouar-FT** [comment]
> Awesome... if you can consider Vue 3 + Test Utils V2 - written in TS. no type problems!

Indeed! Unfortunately, we are still using Vue 2 as we can't migrate to Vue 3 for now.

**Pull request merged**
