### PR TITLE
chore: add lint cache

### PR DESCRIPTION
**Pull request by Simon-He95**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [ ] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `dev` branch.
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] All tests are passing: https://github.com/vuejs/vue-test-utils/blob/dev/.github/CONTRIBUTING.md#development-setup
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by lmiller1990** [comment]
I don't understand the purpose of this PR - should it have changed 70 files?

**Comment by Simon-He95** [comment]
I upgraded the version of prettier so that he has the caching function, but the rules have changed a little.
I did not find that there is a property configured to be the same as before.

image

**Comment by lmiller1990** [comment]
Hm, I guess we can do this.

Can you revert the changes to the files in the `dist` directories? We only update those when we do a release. We probably shouldn't commit these at all, but that's how the project has historically been configured.

**Comment by Simon-He95** [comment]
I have reverted dist and set .eslintignore **/dist/**

**Review by lmiller1990 — APPROVED** [review]

**Comment by lmiller1990** [comment]
thanks!

**Pull request merged**
