### PR TITLE
Trigger options key code fix (fix #1285)

### LINKED ISSUE #1285: Unable to trigger keydown event with custom keyCode
### Version
1.0.0-beta.29

### Reproduction link
[https://github.com/igor-nabebin/vue-test-utils-jest-example](https://github.com/igor-nabebin/vue-test-utils-jest-example)

### Steps to reproduce
1. Clone repo
2. Run "npm install"
3. Run "npm run test"

### What is expected?
A keydown event with keyCode = 65 is fired, test passed.

### What is actually happening?
A keydown event with keyCode = 0 is fired, test failed.

### PR DESCRIPTION
**Pull request by igor-nabebin**
Allowing to specify keyCode option while calling trigger method, throwing warning if both keyCode option and event modifier are specified (keyCode has higher priority so modifier will be ignored in this case).

Related issue #1285 

P.S. Failed CI test is my fault, commit with tests must not be tested separately from the first one.

### CODE REVIEW

**Comment by lmiller1990** [comment]
Hi @igor-nabebin , sorry no-one was able to review your code. Are you still interested in getting this one merged up? If you can get the tests passing and resolve, I can give you a review.

If not, I can probably do those for you - let me know.

**Comment by nabebin** [comment]
Hi, @lmiller1990
I'm still interested in merging this PR and I think I also could make tests pass. The only problem is I've lost access to my account and I can't update the branch, so I'm afraid I'll have to open another PR and this one could be closed.

**Comment by lmiller1990** [comment]
@Lamberthassel I can push some commits to your branch resolving your conflicts if you are busy. Alternatively if you have time to reopen a fresh PR that would be fine too. Your choice! Let me know.

**Comment by nabebin** [comment]
Ah, I've just found out it has already been fixed few months ago.
https://github.com/vuejs/vue-test-utils/pull/1378

I think the PR could be closed.

**Comment by dobromir-hristov** [comment]
Cool, let us know if you find something related that seems broken :)

**Pull request closed without merging**
