### PR TITLE
Emit api

### PR DESCRIPTION
**Pull request by lmiller1990**
Add an alternative syntax for `wrapper.emitted()`.

Also updated docs to include new syntax (ja and en).

### CODE REVIEW

**Comment by lmiller1990** [comment]
In response to #181 

@eddyerburgh , I'm sure I need to add something for Typescript somewhere for this. 

It turned out adding the different syntax was trivial and I was overthinking it. I'm sure you have some feedback or change requests.

Also perhaps @kazupon will check the Japanese translation.

**Comment by lmiller1990** [comment]
Thanks @kazupon .

Also for some reason `createLocalVue Router should work properly with local Vue` was failing locally, but it passes on the CI. Eh.

**Comment by eddyerburgh** [comment]
Are you able to add types? They're in the types/index.d.ts https://github.com/vuejs/vue-test-utils/blob/dev/types/index.d.ts

I can help you if you're stuck 😄

**Comment by lmiller1990** [comment]
I tried to add the types. I think it is just one type, the new optional event string. I haven't used typescript before, is it a big game changer? Should I be? 

Let me know if I should change anything else, @eddyerburgh .

**Pull request merged**
