### PR TITLE
Update common-tips.md

### PR DESCRIPTION
**Pull request by littlefive**

### CODE REVIEW

**Review by Jinjiang — CHANGES_REQUESTED** [review]
@littlefive 这里的英文会作为例子的一部分保留，原因见 https://github.com/vuejs/vue-test-utils/pull/1167#pullrequestreview-210620009
@kazupon not sure why but it's the exactly the same to #1167😅 so update not necessary.

Thanks.

**Comment by littlefive** [comment]
那为什么

```
<template>
  <div>
    <child-component @custom="onCustom" />
    <p v-if="emitted">触发！</p>
  </div>
</template>
```
这个要翻译成中文?
请保持整个例子的可执行性，这个是demo最基本的要求吧。
don't make me think。

**Comment by Jinjiang** [comment]
可能翻译的比较早了，我们会抽空统一 (改回英文)

**Comment by kazupon** [comment]
@Jinjiang
Thanks reviewing!

I think the change is not necessary.

@littlefive
>not sure why but it's the exactly the same to #1167😅 so update not necessary.

close for this reason.
Thank you for your feedback.

**Pull request closed without merging**
